export default {
    word: [
        {id: 0, value: 'B', visible: false},
        {id: 1, value: 'E', visible: false},
        {id: 2, value: ' ', visible: false},
        {id: 3, value: 'C', visible: false},
        {id: 4, value: 'A', visible: false},
        {id: 5, value: 'R', visible: false},
        {id: 6, value: 'E', visible: false},
        {id: 7, value: 'F', visible: false},
        {id: 8, value: 'U', visible: false},
        {id: 9, value: 'L', visible: false},
        {id: 10, value: 'L', visible: false},
        {id: 11, value: ' ', visible: false},
        {id: 12, value: 'E', visible: false},
        {id: 13, value: 'A', visible: false},
        {id: 14, value: 'C', visible: false},
        {id: 15, value: 'H', visible: false},
        {id: 16, value: ' ', visible: false},
        {id: 17, value: 'L', visible: false},
        {id: 18, value: 'E', visible: false},
        {id: 19, value: 'T', visible: false},
        {id: 20, value: 'T', visible: false},
        {id: 21, value: 'E', visible: false},
        {id: 22, value: 'R', visible: false},
        {id: 23, value: ' ', visible: false},
        {id: 24, value: 'C', visible: false},
        {id: 25, value: 'A', visible: false},
        {id: 26, value: 'N', visible: false},
        {id: 27, value: ' ', visible: false},
        {id: 28, value: 'K', visible: false},
        {id: 29, value: 'I', visible: false},
        {id: 30, value: 'L', visible: false},
        {id: 31, value: 'L', visible: false},
        {id: 32, value: ' ', visible: false},
        {id: 33, value: 'Y', visible: false},
        {id: 34, value: 'O', visible: false},
        {id: 35, value: 'U', visible: false},
    ],
    tries: 5,
    gameOver: false
}